#!/bin/sh

set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure|reconfigure)
        # Задаем вопросы
        db_input critical r7mailfilter/db-host || true
        db_input critical r7mailfilter/db-port || true
        db_input critical r7mailfilter/db-name || true
        db_input critical r7mailfilter/db-user || true
        db_input critical r7mailfilter/db-pwd || true
        db_go
        ;;
esac

exit 0
